export const PoolInputLabel = {
  root_admin: 'Admin address',
  logo: 'Logo',
  contract_address: 'Pool contract',
  token_y: 'Pool account',
  name: 'Pool name',
  tag_line: 'Tagline',
  website: 'Website',
  token_economic: 'Token economic',
  twitter: 'Twitter',
  medium: 'Medium',
  telegram: 'Telegram',
  pool_start: 'Start Date',
  description: 'Description',
  token_address: 'Token address',
  token_name: 'Token name',
  token_symbol: 'Token symbol',
  token_decimals: 'Decimal',
  token_total_supply: 'Total supply',
  join_pool_start: 'Join pool start',
  join_pool_end: 'Join pool end',
  claim_at: 'Claim start',
  early_phase_is_active: 'ISOLA whitelist users round',
  max_allocation_all_phases: 'Total raise',
  early_phase_max_total_alloc: 'Total raise in ISOLA whitelist users round',
  token_ratio: 'Swap ratio',
  early_join_duration: 'Duration of ISOLA whitelist users round (minutes)',
  token_to: 'Tokens per',
  public_phase_max_individual_alloc: 'Max contribution size',
  audit_link: 'Audit link',
  liquidity_percentage: 'Liquidity percentage',
  claimable_percentage: 'Claimable percentage',
  fcfs_stake_duration: 'Duration of ISOLA FCFS for stakers round( minutes)',
  fcfs_stake_phase_multiplication_rate:
    'Multiplication rate in FCFS for stakers round',
  exclusive_phase_is_active: 'ISOLA exclusive round',
  exclusive_join_duration: 'Duration of ISOLA exclusive round (minutes)',
  exclusive_phase_max_total_alloc: 'Total raise in ISOLA exclusive round',
  fcfs_stake_phase_is_active: 'ISOLA fcfs for stakers round',
  voting_start: 'Voting time start',
  voting_end_1: 'Voting time end (no more than ',
  voting_end_2: ' days)',
};
